[package]
name = "starknet_function_permit"
version = "0.0.1"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
openzeppelin = "0.17.0"

[dev-dependencies]
snforge_std = "0.30.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
